recommendation = {
  "Apple___Healthy": "Monitor for early signs of fungal issues; maintain balanced fertilization and perform winter pruning.",
  "Tomato___Early_blight": "Implement a 3-year crop rotation, stake plants to improve airflow, and apply protective fungicides (e.g., chlorothalonil) as needed.",
  "Potato___Late_blight": "Immediately remove and destroy infected foliage and tubers. Apply systemic fungicides and ensure proper hilling to cover tubers.",
  "Pepper_bell___Bacterial_spot": "Use copper-based bactericides at the start of the season. Avoid all overhead watering to reduce bacterial splash and spread.",
  "Apple___Black_rot": "Prune out dead wood and cankers during dormancy. Apply fungicides (e.g., captan) from the pink bud stage through early cover sprays.",
  "Apple___Cedar_apple_rust": "Apply fungicides (e.g., myclobutanil) beginning at the pink bud stage. If possible, remove nearby juniper hosts to break the disease cycle.",
  "Rice___Blast": "Use resistant cultivars when planting. Optimize nitrogen fertilizer use (avoid excess). Apply strobilurin fungicides if the disease is severe.",
  "Rice___Brown_Spot": "Use certified clean seeds and manage field water levels to avoid stress. Apply appropriate foliar fungicides upon detection.",
  "Tomato___Septoria_leaf_spot": "Remove the oldest, lowest infected leaves immediately. Mulch heavily to prevent soil splash and apply a protective fungicide.",
  "Tomato___Leaf_Mold": "In greenhouse settings, improve ventilation to reduce humidity. In fields, use resistant varieties and protective fungicides.",
  "Wheat___Healthy": "Maintain standard farming practices. Monitor soil pH and nutrient levels regularly to ensure optimal growth conditions.",
  "Wheat___Leaf_Rust": "Plant rust-resistant varieties for the next season. Apply labeled fungicides (e.g., triazole) early upon the first sign of symptoms.",
  "Cassava___Mosaic": "Use only certified virus-free planting material (cuttings). Uproot and destroy all infected plants immediately upon sight.",
  "Cassava___Brown_Streak": "Use clean propagation material. Plant in cooler, higher elevations where the disease vector is less active.",
  "Almond___Scab": "Apply fungicides (e.g., azoxystrobin) at petal fall and first cover spray. Prune trees to encourage better air circulation.",
  "Almond___Leaf_Blight": "Apply copper fungicides during the dormant season and early spring. Improve overall irrigation management to reduce stress.",
  "Sugarcane___Red_Rot": "Plant resistant cane varieties to prevent infection. Destroy affected stubble and setts immediately after harvest.",
  "Potato___Early_blight": "Implement crop rotation and deep mulch. Apply protective fungicides before symptoms become widespread or when weather favors disease.",
  "Potato___Healthy": "Maintain consistent soil moisture, fertilize according to soil test recommendations, and scout regularly for emerging pests or diseases.",
  "Pepper_bell___Healthy": "Ensure good soil health, consistent moisture, and appropriate sun exposure (6-8 hours daily).",
  "Corn___Common_rust": "Select and plant resistant hybrids for future seasons. Fungicides are an option for high-value crops if the infection is detected early.",
  "Corn___Gray_leaf_spot": "Rotate corn with non-host crops (like soybeans). Use minimum tillage to help decompose infected residue quickly.",
  "Corn___Northern_Leaf_Blight": "Plant resistant hybrids (those rated 'R' or 'MR'). Consider fungicide application if conditions favor rapid disease spread.",
  "Sugarcane___Grassy_Shoot": "Use hot-water treated setts for planting. Remove and destroy infected clumps as they appear in the field.",
  "Tea___Red_Rust": "Improve bush health with proper nutrition, especially potassium. Apply copper oxychloride in cases of severe infestation.",
  "Grape___Esca_(Black_Measles)": "Prune late in the dormant season. Apply protective paste or fungicide to fresh pruning wounds to prevent spore entry.",
  "Grape___Black_rot": "Remove and destroy all mummified berries from the vineyard floor and vines. Apply fungicides (e.g., mancozeb) starting at bud break.",
  "Grape___Isariopsis_Leaf_Spot_(Sooty_Mold)": "Improve canopy airflow via strategic pruning to reduce humidity. Apply fungicides as warranted by weather conditions.",
  "Tea___Algal_Leaf_Spot": "Improve drainage and soil aeration in the tea garden. Remove and destroy severely affected branches and leaves.",
  "Pomegranate___Bacterial_Blight": "Prune out all infected branches during the dry season. Apply copper-based fungicides at bud break and early fruit set.",
  "Cherry___Powdery_mildew": "Apply wettable sulfur or biological fungicides (e.g., bacillus subtilis). Prune to open the canopy and improve sunlight penetration.",
  "Cherry___Healthy": "Maintain consistent watering and fertilization. Protect developing buds and flowers from late-spring frost events.",
  "Cherry___Shot_hole": "Rake and destroy fallen leaves in the fall. Apply copper sprays post-harvest and again at leaf drop.",
  "Peach___Bacterial_spot": "Use highly resistant cultivars. Apply copper sprays during the dormant season and early spring to manage inoculum.",
  "Peach___Healthy": "Maintain proper pruning and strategic fruit thinning to ensure good air circulation and quality fruit development.",
  "Peach___Leaf_curl": "Apply a dormant-season fungicide (e.g., chlorothalonil or copper) thoroughly before the buds begin to swell in late winter.",
  "Strawberry___Leaf_scorch": "Use resistant varieties in future plantings. Apply fungicides (e.g., azoxystrobin) if the disease is confirmed early.",
  "Strawberry___Healthy": "Ensure raised beds for excellent drainage. Use drip irrigation to keep foliage dry and reduce the risk of disease.",
  "Strawberry___Angular_leaf_spot": "Use certified disease-free plants. Avoid overhead irrigation and apply copper if the infection is confirmed.",
  "Soybean___Healthy": "Monitor for minor nutrient deficiencies and maintain excellent weed control to limit competition and stress.",
  "Soybean___Bacterial_blight": "Plant resistant varieties and always use certified, clean seed. Implement a strong crop rotation program.",
  "Squash___Powdery_mildew": "Apply horticultural oils or sulfur fungicides upon sighting. Select resistant squash varieties for future planting.",
  "Squash___Gummy_stem_blight": "Practice crop rotation with non-cucurbit crops. Apply protective fungicides on a weekly schedule during the growing season.",
  "Squash___Healthy": "Water deeply at the base of the plant to keep leaves dry. Provide a trellis or staking for optimal air circulation.",
  "Pomegranate___Healthy": "Prune root suckers regularly. Ensure consistent, deep watering during dry periods, especially as fruit develops.",
  "Raspberry___Healthy": "Plant in well-drained soil and avoid wet, heavy clay. Prune out old fruiting canes immediately after harvest.",
  "Raspberry___Leaf_spot": "Apply fungicides (e.g., captan) only if the disease is severe. Improve cane vigor and reduce moisture around the leaves.",
  "Citrus___Canker": "Remove and destroy infected fruit and branches to limit spread. Apply copper sprays regularly, especially before rain events. ",
  "Citrus___Greening": "The disease is currently incurable; remove and destroy infected trees immediately to protect neighbors. Aggressively control the Asian citrus psyllid vector. ",
  "Plum___Rust": "Apply fungicides (e.g., sulfur) at the first sign of rust lesions. Rake and destroy all fallen, infected leaves in autumn.",
  "Palm___Healthy": "Maintain bright, indirect light and allow the top inch of soil to dry out between waterings. Fertilize lightly during the growing season.",
  "Palm___Spider_mites": "Isolate the plant immediately. Increase humidity, wipe leaves with soapy water, and apply insecticidal soap or neem oil if infestation persists.",
  "Unknown": "Please upload a clearer image or capture the affected area closer. The current image prevents accurate diagnosis."
}

def get_recommendation(label: str) -> str:
    """
    Fetch recommendation text for a given predicted label.
    Returns a generic message if label is not found.
    """
    return recommendation.get(label, "No recommendation available.")
